/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.t4atf.wiremock

import com.github.tomakehurst.wiremock.client.WireMock
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.cloud.contract.wiremock.AutoConfigureWireMock

@SpringBootTest
@AutoConfigureWireMock(port = 0)
class AppTest {
	companion object {
		@BeforeAll
		@JvmStatic
		fun init() {
			WireMock.stubFor(
				WireMock.get(WireMock.urlPathMatching("/test"))
					.willReturn(
						WireMock.ok()
					)
			)
		}
	}

	@Test
	fun test() {

	}
}
